# задача 1
Выполнить операции над матрицами:

\
$$
A = \begin{pmatrix}
1 & 2 & 1\\
-2 & 1 & 1
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
3 & 1\\
-1 & 0\\
2 & 4
\end{pmatrix}
$$

$$
C = \begin{pmatrix}
-2 & 2\\
1 & -1\\
1 & 2
\end{pmatrix}
$$


**A + 2B = ?**

**B + 2C = ?**

In [14]:
import numpy as np
A = np.matrix([[1, 2, 1], [-2, 1, 1]])
B = np.matrix([[3, 1], [-1, 0], [2, 4]])
C = np.matrix([[-2, 2], [1, -1], [1, 2]])
Bt = np.transpose(B)
print(A + 2 * Bt)
print()
print(B + 2 * C)

[[7 0 5]
 [0 1 9]]

[[-1  5]
 [ 1 -2]
 [ 4  8]]


# задача 2
Создать матрицу размером 8х8 элементов, состоящую из нулей.

Заполнить эту матрицу значениями, расположенными в шахматном порядке.

Задачу решить через срезы массива NumPy.

In [2]:
import numpy as np
A = np.zeros((8, 8))
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# задача 3

1.   Сформировать два вектора: первый длиной 15 элементов со значениями от 0 до 1,4 с шагом 0,1; второй – длиной 6 элементов со значениями от 1 до 6.
2.   Преобразовать первый вектор в матрицу 5х3, а второй – в матрицу 3х2. Выполнить перемножение этих матриц. Сами матрицы и результат их перемножения вывести на экран.


In [15]:
import numpy as np
A = np.linspace(0, 1.4, 15).reshape(5, 3)
B = np.linspace(1, 6, 6).reshape(3, 2)
print(A)
print()
print(B)
print()
print(np.asmatrix(A) * np.asmatrix(B))

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]

[[1. 2.]
 [3. 4.]
 [5. 6.]]

[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


# задача 4

1.   Сформировать вектор из целых чисел (тип элементов должен быть int32) размерностью 36 и значениями 1,3,5,7,...и так далее
2.   Выделить из этого вектора все элементы со значениями кратными 3. Вывести результат на экран (исходный вектор и с кратными числами).


In [12]:
import numpy as np
vector = np.arange(1, 72, 2, dtype=np.int32)
print(vector)
vector_filtered = vector[np.where(vector % 3 == 0)]
print(vector_filtered)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
[ 3  9 15 21 27 33 39 45 51 57 63 69]
